### ISSUE TITLE
Support gatsby version 5

### ISSUE THREAD

**Issue by abhith** [thundermiracle/gatsby-remark-prismjs-copy-button#52]
![image](https://github.com/thundermiracle/gatsby-remark-prismjs-copy-button/assets/7039457/cdfde8ac-7045-436e-af3a-5a71bd7eb241)

**Comment by gizmomkd** [comment]
looking for solution to this plugin to support Gatsby v5 👍

**Comment by thundermiracle** [comment]
v0.4.0 released.
It works fine in GatsbyJS@v5, just updated the peerDependencies and published it.

https://github.com/thundermiracle/gatsby-remark-prismjs-copy-button/releases/tag/v0.4.0

**Comment by abhith** [comment]
Hey @thundermiracle, thanks for the update.

I noticed that the warning has disappeared, but I'm still having trouble getting the copy button to appear on the code blocks. In my situation, the content is in `*.mdx` format, and I made the necessary configuration changes for this plugin under the `gatsbyRemarkPlugins` section in the `gatsby-plugin-mdx` configuration. You can check out the relevant changes here: [link to GitHub pull request](https://github.com/abhith/abhith.net/pull/1806/files).

I can see that the plugin styles are being injected into the pages, but the copy button is missing on the code blocks. Here's an example of what I'm seeing: ![image](https://github.com/thundermiracle/gatsby-remark-prismjs-copy-button/assets/7039457/dcc1d5c1-052d-49fe-ab07-4d6c57996db9)

You can find a sample code block here: [link to code block](https://abhith-net-git-1790-code-block-copy-button-abhith.vercel.app/blog/cost-optimization-auto-shutdown-and-startup-of-tagged-vms-with-azure-automation/#implementing-vm-startup-with-azure-automation).

If this plugin doesn't support `mdx`, please let me know, and I'll close the issue and look for alternative solutions. :)

**Comment by thundermiracle** [comment]
> If this plugin doesn't support mdx

Yes. As AST of markdown and mdx are different, a plugin cannot support both of them. And this plugin is created for markdown. Must be used with `gatsby-transformer-remark`.
